<datalist id="cities">
<option value="Algarrobo">
<option value="Alto Hospicio">
<option value="Ancud">
<option value="Andacollo">
<option value="Angol">
<option value="Antofagasta">
<option value="Arauco">
<option value="Laraquete">
<option value="Arica">
<option value="Puerto Aysén">
<option value="Buin">
<option value="Alto Jahuel">
<option value="Bulnes">
<option value="Cabildo">
<option value="Puerto Williams">
<option value="Cabrero">
<option value="Monte Águila">
<option value="Calama">
<option value="Calbuco">
<option value="Caldera">
<option value="La Calera">
<option value="Calera de Tango">
<option value="Calle Larga">
<option value="Cañete">
<option value="Carahue">
<option value="Cartagena">
<option value="Casablanca">
<option value="Castro">
<option value="Catemu">
<option value="Cauquenes">
<option value="Cerrillos">
<option value="Cerro Navia">
<option value="Chaitén">
<option value="Chañaral">
<option value="Chépica">
<option value="Chiguayante">
<option value="Chile Chico">
<option value="Chillán">
<option value="Chillán Viejo">
<option value="Chimbarongo">
<option value="Chonchi">
<option value="Cochrane">
<option value="Codegua">
<option value="Coelemu">
<option value="Coihueco">
<option value="Colbún">
<option value="Colina">
<option value="Chicureo">
<option value="Chamisero">
<option value="Collipulli">
<option value="Coltauco">
<option value="Combarbalá">
<option value="Concepción">
<option value="Conchalí">
<option value="Concón">
<option value="Constitución">
<option value="Copiapó">
<option value="Coquimbo">
<option value="Tongoy">
<option value="Coronel">
<option value="Coyhaique">
<option value="Cunco">
<option value="Curacaví">
<option value="Curanilahue">
<option value="Curicó">
<option value="Dalcahue">
<option value="Diego de Almagro">
<option value="El Salvador">
<option value="Lo Miranda">
<option value="Doñihue">
<option value="El Bosque">
<option value="El Monte">
<option value="El Quisco">
<option value="El Tabo">
<option value="Las Cruces">
<option value="Estación Central">
<option value="Freire">
<option value="Fresia">
<option value="Frutillar">
<option value="Futrono">
<option value="Gorbea">
<option value="Graneros">
<option value="Hijuelas">
<option value="Hualañé">
<option value="Hualpén">
<option value="Hualqui">
<option value="Huasco">
<option value="Huechuraba">
<option value="Illapel">
<option value="Independencia">
<option value="Iquique">
<option value="Isla de Maipo">
<option value="La Islita">
<option value="Hanga Roa">
<option value="La Cisterna">
<option value="La Cruz">
<option value="La Florida">
<option value="La Granja">
<option value="La Ligua">
<option value="La Pintana">
<option value="La Reina">
<option value="La Serena">
<option value="La Unión">
<option value="La Laja">
<option value="Lampa">
<option value="Valle Grande">
<option value="Batuco">
<option value="Lanco">
<option value="Las Cabras">
<option value="Las Condes">
<option value="Lautaro">
<option value="Lebu">
<option value="Limache">
<option value="Linares">
<option value="Llaillay">
<option value="Llanquihue">
<option value="Lo Barnechea">
<option value="Lo Espejo">
<option value="Lo Prado">
<option value="Loncoche">
<option value="Longaví">
<option value="Los Álamos">
<option value="Los Andes">
<option value="Los Ángeles">
<option value="Los Lagos">
<option value="Los Muermos">
<option value="Los Vilos">
<option value="Lota">
<option value="Machalí">
<option value="Macul">
<option value="Maipú">
<option value="San José de la Mariquina">
<option value="Culenar">
<option value="Maule">
<option value="Mejillones">
<option value="Melipilla">
<option value="Bollenar">
<option value="Molina">
<option value="Monte Patria">
<option value="El Palqui">
<option value="San Francisco de Mostazal">
<option value="La Punta">
<option value="Mulchén">
<option value="Ñuñoa">
<option value="Nacimiento">
<option value="Nancagua">
<option value="Puerto Natales">
<option value="El Melón">
<option value="Nogales">
<option value="Nueva Imperial">
<option value="Gultro">
<option value="Olmué">
<option value="Osorno">
<option value="Ovalle">
<option value="Padre Hurtado">
<option value="Padre Las Casas">
<option value="Paillaco">
<option value="Paine">
<option value="Hospital">
<option value="Panguipulli">
<option value="Parral">
<option value="Pedro Aguirre Cerda">
<option value="Peñaflor">
<option value="Peñalolén">
<option value="Penco">
<option value="Peralillo">
<option value="Peumo">
<option value="Pichidegua">
<option value="Pichilemu">
<option value="El Principal">
<option value="Pitrufquén">
<option value="Porvenir">
<option value="Pozo Almonte">
<option value="Providencia">
<option value="Las Ventanas">
<option value="Puchuncaví">
<option value="Pucón">
<option value="Pudahuel">
<option value="Ciudad del Valle">
<option value="Puente Alto">
<option value="Puerto Montt">
<option value="Alerce">
<option value="Puerto Varas">
<option value="Punitaqui">
<option value="Punta Arenas">
<option value="Purén">
<option value="Purranque">
<option value="Putaendo">
<option value="Putre">
<option value="Quellón">
<option value="Quilicura">
<option value="Quillón">
<option value="Quillota">
<option value="Quilpué">
<option value="Quinta de Tilcoco">
<option value="Quinta Normal">
<option value="Quintero">
<option value="Quirihue">
<option value="Rancagua">
<option value="Rauco">
<option value="Recoleta">
<option value="Renaico">
<option value="Renca">
<option value="Rengo">
<option value="Requínoa">
<option value="Retiro">
<option value="Rinconada">
<option value="Río Bueno">
<option value="Río Negro">
<option value="Romeral">
<option value="Salamanca">
<option value="San Antonio">
<option value="San Bernardo">
<option value="San Carlos">
<option value="San Clemente">
<option value="San Esteban">
<option value="San Felipe">
<option value="San Fernando">
<option value="San Javier">
<option value="San Joaquín">
<option value="San José de Maipo">
<option value="San Miguel">
<option value="San Pedro de Atacama">
<option value="San Pedro de la Paz">
<option value="San Ramón">
<option value="San Vicente de Tagua Tagua">
<option value="Santa Bárbara">
<option value="Santa Cruz">
<option value="Santa Juana">
<option value="Santa María">
<option value="Santiago">
<option value="Santo Domingo">
<option value="Talagante">
<option value="Talca">
<option value="Talcahuano">
<option value="Taltal">
<option value="Temuco">
<option value="Labranza">
<option value="Teno">
<option value="Tierra Amarilla">
<option value="Tiltil">
<option value="Tocopilla">
<option value="Tomé">
<option value="Traiguén">
<option value="Huépil">
<option value="Valdivia">
<option value="Vallenar">
<option value="Valparaíso">
<option value="Placilla de Peñuelas">
<option value="Victoria">
<option value="Vicuña">
<option value="Vilcún">
<option value="Cajón">
<option value="Villa Alegre">
<option value="Villa Alemana">
<option value="Villarrica">
<option value="Viña del Mar">
<option value="Vitacura">
<option value="Yumbel">
<option value="Yungay">
</datalist>