<?php

use Illuminate\Database\Seeder;

class PaymentTableSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('payments')->insert([
			[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			], // Dia anterior
			[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(1)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(1)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(1)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],// Día anterior
			[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(2)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(2)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(2)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(2)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],// Dia anterior
			[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(3)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(3)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(3)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(3)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(3)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],// Dia anterior
			[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(4)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(4)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(4)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(4)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],// Día anterior
			[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(5)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(5)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(5)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(5)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(5)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],// Dia anterior
			[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(6)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(6)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(6)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],// Dia anterior
			[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(7)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(7)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],// Día anterior
			[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(8)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(8)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(8)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],// Día anterior
			[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(9)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],[
				'user_id' => rand(1, 7),
				'worker_id' => rand(1, 7),
				'order_id' => rand(1, 19),
				'token_ws' => Hash::make(Str::random(20)),
				'authorization_code' => rand(1001, 9999),
				'payment_type' => "VD",
				'shares_amount' => 0.0,
				'shares_number' => 0,
				'payment_date' => \Carbon\Carbon::now()->subDay(9)->toDateTimeString(),
				'card_number' => rand(1000, 9999),
				'card_expire_date' => null,
				'worker_paid' => 0,
				'amount' => rand(10000, 100000),
			],
		]);
	}
}
