<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class ServiceOrdersTableSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('service_orders')->insert([
			[
				'user_id' => 1,
				'worker_id' => 4,
				'admin_id' => NULL,
				'service_id' => 2,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 3,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 3,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 1,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 8,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 4,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 2,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 5,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 3,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 6,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 8,
				'status' => 'open',
				'starting_date' => Carbon::now()->adddays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 5,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 8,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 3,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 2,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 7,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 8,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 6,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 3,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 5,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 8,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 4,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 5,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 6,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 7,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 2,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 6,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 1,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 6,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 7,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 2,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 2,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 5,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 4,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 5,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],[
				'user_id' => 3,
				'worker_id' => NULL,
				'admin_id' => NULL,
				'service_id' => 5,
				'status' => 'open',
				'starting_date' => Carbon::now()->addDays(5),
				'ending_date' => Carbon::now()->addDays(7),
				'starting_time' => '09:00:00',
				'ending_time' => '14:00:00',
				'region' => 'Metropolitana',
				'comunity' => 'Santiago',
				'city' => 'Santiago',
				'aditional_info' => 'Información adicional',
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],
		]);
	}
}
